# Dependencies
markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Carson Tang
tagline:          'A Jekyll theme'
description:      'Computer Engineering @ University of Waterloo'
url:              https://carsonkstang.me
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Carson-Tang
email:            mailto:carson.tang@uwaterloo.ca
linkedin:         https://linkedin.com/in/carson-tang

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
